#ifndef NUMERICA_CONSTANTS_HPP
#define NUMERICA_CONSTANTS_HPP

#ifndef NUMERICA_MAX_ARRAY_SIZE
#define NUMERICA_MAX_ARRAY_SIZE 4294967296
#endif

#ifndef NUMERICA_RUNTIME_CHECKS_OFF
#define NUMERICA_RUNTIME_CHECKS_OFF 0
#endif

#endif